### ISSUE TITLE
1.5.15 Update Failure

### ISSUE THREAD

**Issue by Imburr** [QuinnDamerell/OctoPrint-OctoEverywhere#24]
2022-02-21 21:31:30,521 - octoprint.plugins.softwareupdate - INFO - Starting update of octoeverywhere to 1.5.15...
2022-02-21 21:31:30,625 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:30,938 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:31,639 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:32,021 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:32,342 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:32,626 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:32,935 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:33,259 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:33,629 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:33,931 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:34,314 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:34,618 - octoprint.plugins.printoid - INFO - //// Send alert to Printoid: 'printer-state' with value Operational (Ender)
2022-02-21 21:31:47,291 - octoprint.plugins.softwareupdate - ERROR - Update of octoeverywhere can not be performed, please also check plugin_softwareupdate_console.log for possible causes of this
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 2090, in _perform_update
    target, populated_check, target_version, log_cb=self._log, online=online
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 115, in perform_update
    returncode, stdout, stderr = pip_caller.execute(*pip_args, **pip_kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/pip.py", line 208, in execute
    return self.call(command, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 244, in call
    all_stdout += process_stdout(p.stdout.readlines(timeout=0.5))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 236, in process_stdout
    return process_lines(lines, self._log_stdout)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 230, in process_lines
    *map(lambda x: to_unicode(x, errors="replace"), lines)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/pip.py", line 498, in _preprocess_lines
    return list(map(self._preprocess, lines))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/pip.py", line 517, in _preprocess
    return to_unicode(clean_ansi(text))
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/commandline.py", line 57, in clean_ansi
    return _ANSI_REGEX.sub(b"", line.encode("latin1")).decode("latin1")
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-41: ordinal not in range(256)
2022-02-21 21:31:47,439 - octoprint.plugins.softwareupdate - INFO - Saved update log to disk

2022-02-21 21:31:30,544   /home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/QuinnDamerell/OctoPrint-OctoEverywhere/archive/1.5.15.zip --no-cache-dir

**Comment by QuinnDamerell** [comment]
Hey @Imburr! Thanks for the bug report! Can you open a ticket at the following address so we can chat privately over email?

https://octoeverwhere.com/support
